# Generated by Django 5.0.4 on 2024-04-10 09:18

import gcode.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_stlfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=1000)),
                ('file', models.FileField(blank=True, upload_to=gcode.models.upload_to, verbose_name='uploaded_file')),
            ],
        ),
    ]
